import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Ecoquity",
  description: "Generated by create next app",
  icons: {
    icon: {
      rel: "icon",
      url: "/images/favicon.ico",
    },
  },
};

// If loading a variable font, you don't need to specify the font weight
const fontRoboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "700"],
  variable: "--font-family-roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontRoboto.variable}>{children}</body>
    </html>
  );
}
